#!/bin/bash
### BEGIN INIT INFO
# Provides:		canvas_init
# Required-Start: 	$local_fs $remote_fs $network $syslog
# Required-Stop:	$local_fs $remote_fs $network $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# X-Interactive:	true
# Short-Description:	Start/stop Canvas background jobs
### END INIT INFO

set -e

# drop privs if necessary
if [ "$(id -u)" == "0" ]; then
  exec su $(stat -c %U $(dirname $(readlink -f $0))/../config/environment.rb) -c "/bin/bash $0 $@"
  exit -1;
fi

# switch to app root
cd $(dirname $(readlink -f $0))/..

# set up config
if [ -e "config/GEM_HOME" ]; then
  export GEM_HOME=$(cat config/GEM_HOME)
fi
#export GEM_HOME=/path/to/gem/home
export RAILS_ENV=production

# TI-4884
# Ubuntu 22.04 부터는 ruby 2.6을 설치하기 위해서 rvm을 사용합니다.
# /etc/profile.d/rvm.sh 파일이 존재하면 rvm 사용 환경이라고 판단합니다.
# rvm 기반 ruby 2.6이 정상적으로 동작하도록 하기 위해서 rvm.sh 를
# source 하고, 기본 ruby 버전을 ruby-2.6으로 설정합니다.
if [ -e "/etc/profile.d/rvm.sh" ]; then
  source "/etc/profile.d/rvm.sh"
  rvm --default use ruby-2.6
fi

# run delayed jobs
exec script/delayed_job $@
